if ~exist('out','var')
    error('Variabile "out" non trovata. Esegui prima il main.');
end

if ~isprop(out,'z_out') && ~isfield(out,'z_out')
    error('out.z_out non trovato.');
end

if ~isprop(out,'q_out') && ~isfield(out,'q_out')
    error('out.q_out non trovato.');
end

if ~exist('z_r','var')
    error('Variabile "z_r" non trovata nel workspace.');
end

z_out = out.z_out;
q_out = out.q_out;

%%  POSIZIONE
if isa(z_out,'timeseries')
    position = z_out.Data;
    tt = z_out.Time;
else
    error([ ...
        'z_out non e'' un Timeseries.\n' ...
        'Imposta il blocco To Workspace di z_out su:\n' ...
        'Save format = Timeseries']);
end

%% QUATERNIONE
if isa(q_out,'timeseries')
    quaternion = q_out.Data;
else
    error([ ...
        'q_out non e'' un Timeseries.\n' ...
        'Imposta il blocco To Workspace di q_out su:\n' ...
        'Save format = Timeseries']);
end

%% CONTROLLO DIMENSIONI
if size(position,2) ~= 3
    error([ ...
        'z_out deve avere 3 colonne.\n' ...
        'Dimensione trovata: %d colonne.'], ...
        size(position,2));

end

if size(quaternion,2) ~= 4
    error([ ...
        'q_out deve avere 4 colonne.\n' ...
        'Dimensione trovata: %d colonne.'], ...
        size(quaternion,2));
end

if size(position,1) ~= size(quaternion,1)
    error([ ...
        'z_out e q_out devono avere lo stesso numero di campioni.\n' ...
        'z_out = %d campioni\n' ...
        'q_out = %d campioni'], ...
        size(position,1), ...
        size(quaternion,1));

end

%% GEOMETRIA
target = [0;0;0];

standoff = z_r(:);

% Boresight del corpo
boresight_b = [1;0;0];

%% PARAMETRI ANIMAZIONE
nFramesMax = 600;

N = length(tt);

frame_step = max(1,floor(N/nFramesMax));

pause_time = 0.02;

axis_length = 5;

boresight_length = 8;

%% LIMITI GRAFICO
xmin = min(position(:,1));
xmax = max(position(:,1));

ymin = min(position(:,2));
ymax = max(position(:,2));

zmin = min(position(:,3));
zmax = max(position(:,3));

xmin = min(xmin,target(1));
xmax = max(xmax,target(1));

ymin = min(ymin,target(2));
ymax = max(ymax,target(2));

zmin = min(zmin,target(3));
zmax = max(zmax,target(3));

xmin = min(xmin,standoff(1));
xmax = max(xmax,standoff(1));

ymin = min(ymin,standoff(2));
ymax = max(ymax,standoff(2));

zmin = min(zmin,standoff(3));
zmax = max(zmax,standoff(3));

range_max = max([ ...
    xmax-xmin, ...
    ymax-ymin, ...
    zmax-zmin, ...
    1]);

margin = 0.1*range_max;

xmin = xmin-margin;
xmax = xmax+margin;

ymin = ymin-margin;
ymax = ymax+margin;

zmin = zmin-margin;
zmax = zmax+margin;

%% PRE-CALCOLO DCM
R_all = zeros(3,3,N);

x_body_all = zeros(N,3);
y_body_all = zeros(N,3);
z_body_all = zeros(N,3);

los_all = zeros(N,3);

pointing_error_all = zeros(N,1);

for k = 1:N
    % QUATERNIONE
    q = quaternion(k,:)';
    q_norm = norm(q);
    if q_norm < 1e-12
        q = [1;0;0;0];
    else
        q = q/q_norm;
    end  
    % DCM
    R = quat2dcm_local(q);
    R_all(:,:,k) = R;
    % ASSI BODY
    x_body = R*[1;0;0];
    y_body = R*[0;1;0];
    z_body = R*[0;0;1];

    x_body_all(k,:) = x_body';
    y_body_all(k,:) = y_body';
    z_body_all(k,:) = z_body';
    % LOS
    r = position(k,:)';
    los = target-r;
    los_norm = norm(los);
    if los_norm > 1e-12
        los = los/los_norm;
    else
        los = [0;0;0];
    end
    los_all(k,:) = los';
    % ERRORE POINTING
    if los_norm > 1e-12
        cosang = dot(x_body,los);
        cosang = max(min(cosang,1),-1);
        pointing_error_all(k) = acosd(cosang);
    else
        pointing_error_all(k) = 0;
    end
end

%% FIGURA
figure( ...
    'Color','w', ...
    'Name','Animazione 6-DOF', ...
    'NumberTitle','off');

hold on;
grid on;
axis equal;

xlim([xmin xmax]);
ylim([ymin ymax]);
zlim([zmin zmax]);

xlabel('z_1 [m]');
ylabel('z_2 [m]');
zlabel('z_3 [m]');

title('Animazione 6-DOF del Chaser');

view(3);

%% TARGET
h_target = plot3( ...
    target(1), ...
    target(2), ...
    target(3), ...
    'ko', ...
    'MarkerSize',12, ...
    'MarkerFaceColor','r');

%% STANDOFF POINT
h_standoff = plot3( ...
    standoff(1), ...
    standoff(2), ...
    standoff(3), ...
    'ko', ...
    'MarkerSize',10, ...
    'MarkerFaceColor','w');

%% TRAIETTORIA COMPLETA
h_fulltraj = plot3( ...
    position(:,1), ...
    position(:,2), ...
    position(:,3), ...
    '--');

%% CHASER
r0 = position(1,:)';
h_chaser = plot3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    'ko', ...
    'MarkerSize',8, ...
    'MarkerFaceColor','k');

%% TRAIETTORIA PERCORSA
h_traj = plot3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    '-');

%% LOS
los0 = los_all(1,:)';
h_los = plot3( ...
    [r0(1) target(1)], ...
    [r0(2) target(2)], ...
    [r0(3) target(3)], ...
    '--');

%% ASSI BODY
x_body = x_body_all(1,:)';
y_body = y_body_all(1,:)';
z_body = z_body_all(1,:)';

% ASSE X_B
h_x = quiver3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    axis_length*x_body(1), ...
    axis_length*x_body(2), ...
    axis_length*x_body(3), ...
    'LineWidth',2, ...
    'MaxHeadSize',0.5);

% ASSE Y_B
h_y = quiver3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    axis_length*y_body(1), ...
    axis_length*y_body(2), ...
    axis_length*y_body(3), ...
    'LineWidth',2, ...
    'MaxHeadSize',0.5);

% ASSE Z_B
h_z = quiver3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    axis_length*z_body(1), ...
    axis_length*z_body(2), ...
    axis_length*z_body(3), ...
    'LineWidth',2, ...
    'MaxHeadSize',0.5);


%% BORESIGHT
h_boresight = quiver3( ...
    r0(1), ...
    r0(2), ...
    r0(3), ...
    boresight_length*x_body(1), ...
    boresight_length*x_body(2), ...
    boresight_length*x_body(3), ...
    'LineWidth',3, ...
    'MaxHeadSize',0.7);

%% TESTO
h_text = text( ...
    xmin, ...
    ymax, ...
    zmax, ...
    '', ...
    'VerticalAlignment','top', ...
    'FontSize',11);

%% LEGENDA
legend( ...
    [h_fulltraj ...
     h_chaser ...
     h_target ...
     h_standoff ...
     h_los ...
     h_x ...
     h_y ...
     h_z ...
     h_boresight], ...
    {'Traiettoria completa' ...
     'Chaser' ...
     'Target' ...
     'Standoff point' ...
     'LOS' ...
     'Asse X_B' ...
     'Asse Y_B' ...
     'Asse Z_B' ...
     'Boresight'}, ...
    'Location','best');

%% ANIMAZIONE
frame_list = 1:frame_step:N;
for ii = 1:length(frame_list)
    k = frame_list(ii);
    % POSIZIONE
    r = position(k,:)';
    % ASSI BODY
    x_body = x_body_all(k,:)';
    y_body = y_body_all(k,:)';
    z_body = z_body_all(k,:)';
    % CHASER
    set(h_chaser, ...
        'XData',r(1), ...
        'YData',r(2), ...
        'ZData',r(3));
    % TRAIETTORIA PERCORSA
    set(h_traj, ...
        'XData',position(1:k,1), ...
        'YData',position(1:k,2), ...
        'ZData',position(1:k,3));
    % LOS
    set(h_los, ...
        'XData',[r(1) target(1)], ...
        'YData',[r(2) target(2)], ...
        'ZData',[r(3) target(3)]);
    % ASSE X_B
    set(h_x, ...
        'XData',r(1), ...
        'YData',r(2), ...
        'ZData',r(3), ...
        'UData',axis_length*x_body(1), ...
        'VData',axis_length*x_body(2), ...
        'WData',axis_length*x_body(3));
    % ASSE Y_B
    set(h_y, ...
        'XData',r(1), ...
        'YData',r(2), ...
        'ZData',r(3), ...
        'UData',axis_length*y_body(1), ...
        'VData',axis_length*y_body(2), ...
        'WData',axis_length*y_body(3));
    % ASSE Z_B
    set(h_z, ...
        'XData',r(1), ...
        'YData',r(2), ...
        'ZData',r(3), ...
        'UData',axis_length*z_body(1), ...
        'VData',axis_length*z_body(2), ...
        'WData',axis_length*z_body(3));
    % BORESIGHT
    set(h_boresight, ...
        'XData',r(1), ...
        'YData',r(2), ...
        'ZData',r(3), ...
        'UData',boresight_length*x_body(1), ...
        'VData',boresight_length*x_body(2), ...
        'WData',boresight_length*x_body(3));
    % TESTO
    set(h_text, ...
        'String',sprintf([ ...
            't = %.2f s\n' ...
            'Pointing error = %.3f deg'], ...
            tt(k), ...
            pointing_error_all(k)));
    % AGGIORNAMENTO GRAFICO
    drawnow limitrate;
    if pause_time > 0
        pause(pause_time);
    end

end

function R = quat2dcm_local(q)

    q0 = q(1);
    q1 = q(2);
    q2 = q(3);
    q3 = q(4);
    
    % DCM body -> LVLH
    
    R = [1-2*(q2^2+q3^2),  2*(q1*q2-q0*q3),  2*(q1*q3+q0*q2);
        2*(q1*q2+q0*q3),   1-2*(q1^2+q3^2),  2*(q2*q3-q0*q1);
        2*(q1*q3-q0*q2),   2*(q2*q3+q0*q1),  1-2*(q1^2+q2^2)];
end
